# Generated by Django 4.2.6 on 2023-10-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('image', models.CharField()),
                ('contact', models.CharField()),
                ('address', models.TextField()),
                ('country', models.CharField()),
                ('state', models.CharField()),
                ('city', models.CharField()),
                ('zip', models.CharField()),
                ('rating', models.CharField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'places',
            },
        ),
    ]
