# Generated by Django 4.2.6 on 2023-10-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='contact',
            field=models.CharField(null=True),
        ),
    ]
