# Generated by Django 4.2.6 on 2023-10-25 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(primary_key=True, serialize=False)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.CharField()),
                ('mobile', models.CharField()),
                ('image_path', models.CharField()),
                ('password', models.CharField()),
                ('sso_sign_in', models.CharField()),
                ('address', models.TextField()),
                ('work_location', models.TextField()),
                ('email_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UsersSavedPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'users_saved_places',
            },
        ),
    ]
